[build]
builder = "DOCKERFILE"

[[build.buildArgs]]
name = "VITE_API_URL"
value = "$VITE_API_URL"

[[build.buildArgs]]
name = "VITE_CLERK_PUBLISHABLE_KEY"
value = "$VITE_CLERK_PUBLISHABLE_KEY"

[deploy]
startCommand = "nginx -g 'daemon off;'"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
